name: Build release APK

on:
  workflow_dispatch:
  push:
    branches:
      - 12.1-alpha

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepRelease
      - name: Sign release APK
        uses: r0adkll/sign-android-release@v1
        id: sign-release-apk
        with:
          releaseDirectory: build/outputs/apk/lawnWithQuickstep/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Rename artifact
        continue-on-error: true
        run: |
          oldArtifactPath="${{ steps.sign-release-apk.outputs.signedReleaseFile }}"
          newArtifactPath="${oldArtifactPath%'-signed.apk'}.apk"
          echo "ARTIFACT_PATH=$newArtifactPath" >> $GITHUB_ENV
          mv "$oldArtifactPath" "$newArtifactPath"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release APK
          path: ${{ env.ARTIFACT_PATH }}
